name: Deploy to Cloudflare Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'default_config.json'
jobs:
  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    concurrency: build-web
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1 
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          projectName: config
          directory: dist
