name: Publish rule
on:
  repository_dispatch:
    types:
      - deploy-rule-dev
  workflow_dispatch:
    inputs:
      branch:
        default: "develop"
        description: "branch"
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: nightly-build-rule
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: immersive-translate/extension
          ref: ${{github.event.inputs.branch || 'develop'}}
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Clone repo
        run: git clone https://$PERSONAL_GITHUB_TOKEN@github.com/immersive-translate/config repo
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.2
      - name: test
        run: make test
      - id: set_var
        run: |
          content=`cat ./manifest.json`
          echo "::set-output name=version::$(echo $content | jq -r '.version')"
      - name: add buildinConfigUpdatedAt field to repo/dist/default_config.json
        run: make generateconfig target=repo/dist/default_config.json
      - name: checkout target version 
        run: git checkout v${{ steps.set_var.outputs.version }} 
      - name: diff config
        run: make diff-config baseConfig=default_config.json latestConfig=repo/dist/default_config.json outputDiffConfig=repo/dist/diff_config.json
      - name: echo diff config
        run: cat repo/dist/diff_config.json
      # - name: build worker
      #   run: cd repo && make build
      # - name: Deploy worker
      #   uses: cloudflare/wrangler-action@v3
      #   with:
      #     apiToken: ${{ secrets.IMMERSIVE_CLOUDFLARE_API_TOKEN }}
      #     accountId: ${{secrets.IMMERSIVE_CLOUDFLARE_ACCOUNT_ID}}
      #     workingDirectory: ./
      #     command: deploy ./.cache/worker.js
